name: build-airflow
on:
  push:
    branches: [ main ]
    paths: ["airflow/**", "airflow/dags/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: tags
      run: |
        echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        echo "DATE_TAG=v$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

    - uses: docker/build-push-action@v5
      with:
        context: ./airflow
        tags: |
          ziadmmhassanin/airflow:${{ steps.tags.outputs.TAG }}
          ziadmmhassanin/airflow:${{ steps.tags.outputs.DATE_TAG }}
          ziadmmhassanin/airflow:latest
        push: true
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    # bump Helm values so ArgoCD / helm-upgrade picks it up
    - name: Patch Helm values
      run: |
        sed -i "s|airflow:[^\"]*|airflow:${{ steps.tags.outputs.TAG }}|" helm/airflow-values.yaml
    - name: Commit + push
      run: |
        git config user.name CI && git config user.email ci@users.noreply.github.com
        git add helm/airflow-values.yaml
        git commit -m "chore(chart): airflow image → ${{ steps.tags.outputs.TAG }}"
        git push
